"""phase7_bill_pay

Revision ID: 190bd4d83339
Revises: 2aa51f9a515b
Create Date: 2026-06-21 10:37:09.236852
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '190bd4d83339'
down_revision: Union[str, None] = '2aa51f9a515b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_payees',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_bill_payees_user_id'), 'bill_payees', ['user_id'], unique=False)
    op.create_table('bill_payments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('payee_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('scheduled_date', sa.String(length=50), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payee_id'], ['bill_payees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_bill_payments_reference'), 'bill_payments', ['reference'], unique=True)
    op.create_index(op.f('ix_bill_payments_user_id'), 'bill_payments', ['user_id'], unique=False)
    op.create_table('bill_schedules',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('payee_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('next_payment_date', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payee_id'], ['bill_payees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_bill_schedules_user_id'), 'bill_schedules', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'transfer_templates', ['id'])
    op.create_unique_constraint(None, 'transfers', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfers', type_='unique')
    op.drop_constraint(None, 'transfer_templates', type_='unique')
    op.drop_index(op.f('ix_bill_schedules_user_id'), table_name='bill_schedules')
    op.drop_table('bill_schedules')
    op.drop_index(op.f('ix_bill_payments_user_id'), table_name='bill_payments')
    op.drop_index(op.f('ix_bill_payments_reference'), table_name='bill_payments')
    op.drop_table('bill_payments')
    op.drop_index(op.f('ix_bill_payees_user_id'), table_name='bill_payees')
    op.drop_table('bill_payees')
    # ### end Alembic commands ###
