"""phase3_accounts_tables

Revision ID: 20a164cf82cd
Revises: 9880cb1ba140
Create Date: 2026-06-21 06:19:09.908283
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '20a164cf82cd'
down_revision: Union[str, None] = '9880cb1ba140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('available_balance', sa.Float(), nullable=False),
    sa.Column('pending_balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('overdraft_protection', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('account_balances',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('balance_date', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('closing_balance', sa.Float(), nullable=False),
    sa.Column('total_credits', sa.Float(), nullable=False),
    sa.Column('total_debits', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_account_balances_account_id'), 'account_balances', ['account_id'], unique=False)
    op.create_table('account_statements',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('closing_balance', sa.Float(), nullable=False),
    sa.Column('total_deposits', sa.Float(), nullable=False),
    sa.Column('total_withdrawals', sa.Float(), nullable=False),
    sa.Column('total_fees', sa.Float(), nullable=False),
    sa.Column('interest_earned', sa.Float(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_account_statements_account_id'), 'account_statements', ['account_id'], unique=False)
    op.create_unique_constraint(None, 'user_beneficiaries', ['id'])
    op.create_unique_constraint(None, 'user_documents', ['id'])
    op.create_unique_constraint(None, 'user_limits', ['id'])
    op.create_unique_constraint(None, 'user_linked_accounts', ['id'])
    op.create_unique_constraint(None, 'user_notes', ['id'])
    op.create_unique_constraint(None, 'user_tags', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tags', type_='unique')
    op.drop_constraint(None, 'user_notes', type_='unique')
    op.drop_constraint(None, 'user_linked_accounts', type_='unique')
    op.drop_constraint(None, 'user_limits', type_='unique')
    op.drop_constraint(None, 'user_documents', type_='unique')
    op.drop_constraint(None, 'user_beneficiaries', type_='unique')
    op.drop_index(op.f('ix_account_statements_account_id'), table_name='account_statements')
    op.drop_table('account_statements')
    op.drop_index(op.f('ix_account_balances_account_id'), table_name='account_balances')
    op.drop_table('account_balances')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
