"""phase6_transfers

Revision ID: 2aa51f9a515b
Revises: 57c0baabe86f
Create Date: 2026-06-21 10:27:55.265849
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '2aa51f9a515b'
down_revision: Union[str, None] = '57c0baabe86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_templates',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('transfer_type', sa.String(length=50), nullable=False),
    sa.Column('from_account_id', sa.String(length=36), nullable=False),
    sa.Column('to_account_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('recipient_account', sa.String(length=50), nullable=True),
    sa.Column('recipient_routing', sa.String(length=20), nullable=True),
    sa.Column('recipient_bank', sa.String(length=200), nullable=True),
    sa.Column('swift_code', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('next_run_date', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_transfer_templates_user_id'), 'transfer_templates', ['user_id'], unique=False)
    op.create_table('transfers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('from_account_id', sa.String(length=36), nullable=False),
    sa.Column('to_account_id', sa.String(length=36), nullable=True),
    sa.Column('transfer_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('converted_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('recipient_account', sa.String(length=50), nullable=True),
    sa.Column('recipient_routing', sa.String(length=20), nullable=True),
    sa.Column('recipient_bank', sa.String(length=200), nullable=True),
    sa.Column('swift_code', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_transfers_reference'), 'transfers', ['reference'], unique=True)
    op.create_index(op.f('ix_transfers_user_id'), 'transfers', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'withdrawal_methods', ['id'])
    op.create_unique_constraint(None, 'withdrawals', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdrawals', type_='unique')
    op.drop_constraint(None, 'withdrawal_methods', type_='unique')
    op.drop_index(op.f('ix_transfers_user_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_reference'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_transfer_templates_user_id'), table_name='transfer_templates')
    op.drop_table('transfer_templates')
    # ### end Alembic commands ###
