"""phase2_user_profile_tables

Revision ID: 510d3fcc190f
Revises: 8ab9d1c07e8c
Create Date: 2026-06-21 05:51:22.226046
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '510d3fcc190f'
down_revision: Union[str, None] = '8ab9d1c07e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_2fa', ['id'])
    op.create_unique_constraint(None, 'user_activity_logs', ['id'])
    op.create_unique_constraint(None, 'user_devices', ['id'])
    op.create_unique_constraint(None, 'user_login_history', ['id'])
    op.create_unique_constraint(None, 'user_notification_preferences', ['id'])
    op.create_unique_constraint(None, 'user_notifications', ['id'])
    op.create_unique_constraint(None, 'user_profiles', ['id'])
    op.create_unique_constraint(None, 'user_security_questions', ['id'])
    op.create_unique_constraint(None, 'user_sessions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_constraint(None, 'user_security_questions', type_='unique')
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_constraint(None, 'user_notifications', type_='unique')
    op.drop_constraint(None, 'user_notification_preferences', type_='unique')
    op.drop_constraint(None, 'user_login_history', type_='unique')
    op.drop_constraint(None, 'user_devices', type_='unique')
    op.drop_constraint(None, 'user_activity_logs', type_='unique')
    op.drop_constraint(None, 'user_2fa', type_='unique')
    # ### end Alembic commands ###
