"""phase5_withdrawals

Revision ID: 57c0baabe86f
Revises: e1fabe2a4ed7
Create Date: 2026-06-21 10:18:40.488628
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '57c0baabe86f'
down_revision: Union[str, None] = 'e1fabe2a4ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_methods',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('fee_amount', sa.Float(), nullable=False),
    sa.Column('processing_time', sa.String(length=100), nullable=True),
    sa.Column('requires_admin_approval', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('withdrawals',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('method_data', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_withdrawals_reference'), 'withdrawals', ['reference'], unique=True)
    op.create_index(op.f('ix_withdrawals_user_id'), 'withdrawals', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'crypto_networks', ['id'])
    op.create_unique_constraint(None, 'crypto_transactions', ['id'])
    op.create_unique_constraint(None, 'crypto_wallets', ['id'])
    op.create_unique_constraint(None, 'deposit_methods', ['id'])
    op.create_unique_constraint(None, 'deposit_sessions', ['id'])
    op.create_unique_constraint(None, 'deposits', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deposits', type_='unique')
    op.drop_constraint(None, 'deposit_sessions', type_='unique')
    op.drop_constraint(None, 'deposit_methods', type_='unique')
    op.drop_constraint(None, 'crypto_wallets', type_='unique')
    op.drop_constraint(None, 'crypto_transactions', type_='unique')
    op.drop_constraint(None, 'crypto_networks', type_='unique')
    op.drop_index(op.f('ix_withdrawals_user_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_reference'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_table('withdrawal_methods')
    # ### end Alembic commands ###
