"""phase2_missing_tables

Revision ID: 9880cb1ba140
Revises: 510d3fcc190f
Create Date: 2026-06-21 06:03:22.878166
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '9880cb1ba140'
down_revision: Union[str, None] = '510d3fcc190f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_beneficiaries',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('routing_number', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_beneficiaries_user_id'), 'user_beneficiaries', ['user_id'], unique=False)
    op.create_table('user_documents',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_documents_user_id'), 'user_documents', ['user_id'], unique=False)
    op.create_table('user_limits',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('daily_deposit_limit', sa.Float(), nullable=True),
    sa.Column('daily_withdrawal_limit', sa.Float(), nullable=True),
    sa.Column('daily_transfer_limit', sa.Float(), nullable=True),
    sa.Column('per_transaction_limit', sa.Float(), nullable=True),
    sa.Column('monthly_deposit_limit', sa.Float(), nullable=True),
    sa.Column('monthly_withdrawal_limit', sa.Float(), nullable=True),
    sa.Column('card_spending_limit', sa.Float(), nullable=True),
    sa.Column('atm_withdrawal_limit', sa.Float(), nullable=True),
    sa.Column('override_reason', sa.String(length=500), nullable=True),
    sa.Column('overridden_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_linked_accounts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('routing_number', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=20), nullable=True),
    sa.Column('micro_deposit_1', sa.Float(), nullable=True),
    sa.Column('micro_deposit_2', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('plaid_token', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_linked_accounts_user_id'), 'user_linked_accounts', ['user_id'], unique=False)
    op.create_table('user_notes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_notes_user_id'), 'user_notes', ['user_id'], unique=False)
    op.create_table('user_tags',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('applied_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_tags_user_id'), 'user_tags', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tags_user_id'), table_name='user_tags')
    op.drop_table('user_tags')
    op.drop_index(op.f('ix_user_notes_user_id'), table_name='user_notes')
    op.drop_table('user_notes')
    op.drop_index(op.f('ix_user_linked_accounts_user_id'), table_name='user_linked_accounts')
    op.drop_table('user_linked_accounts')
    op.drop_table('user_limits')
    op.drop_index(op.f('ix_user_documents_user_id'), table_name='user_documents')
    op.drop_table('user_documents')
    op.drop_index(op.f('ix_user_beneficiaries_user_id'), table_name='user_beneficiaries')
    op.drop_table('user_beneficiaries')
    # ### end Alembic commands ###
