"""phase8_cards

Revision ID: 9e36afe2391c
Revises: 190bd4d83339
Create Date: 2026-06-21 10:50:13.706676
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '9e36afe2391c'
down_revision: Union[str, None] = '190bd4d83339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('card_number', sa.String(length=20), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('expiry_month', sa.String(length=2), nullable=False),
    sa.Column('expiry_year', sa.String(length=4), nullable=False),
    sa.Column('cvv', sa.String(length=5), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('cardholder_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('daily_spending_limit', sa.Float(), nullable=False),
    sa.Column('per_transaction_limit', sa.Float(), nullable=False),
    sa.Column('atm_withdrawal_limit', sa.Float(), nullable=False),
    sa.Column('online_purchases', sa.Boolean(), nullable=False),
    sa.Column('international', sa.Boolean(), nullable=False),
    sa.Column('contactless', sa.Boolean(), nullable=False),
    sa.Column('apple_pay', sa.Boolean(), nullable=False),
    sa.Column('google_pay', sa.Boolean(), nullable=False),
    sa.Column('samsung_pay', sa.Boolean(), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_cards_user_id'), 'cards', ['user_id'], unique=False)
    op.create_table('card_limits',
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('daily_spending', sa.Float(), nullable=False),
    sa.Column('per_transaction', sa.Float(), nullable=False),
    sa.Column('atm_withdrawal', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_card_limits_card_id'), 'card_limits', ['card_id'], unique=False)
    op.create_table('card_transactions',
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_card_transactions_card_id'), 'card_transactions', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_transactions_user_id'), 'card_transactions', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'bill_payees', ['id'])
    op.create_unique_constraint(None, 'bill_payments', ['id'])
    op.create_unique_constraint(None, 'bill_schedules', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bill_schedules', type_='unique')
    op.drop_constraint(None, 'bill_payments', type_='unique')
    op.drop_constraint(None, 'bill_payees', type_='unique')
    op.drop_index(op.f('ix_card_transactions_user_id'), table_name='card_transactions')
    op.drop_index(op.f('ix_card_transactions_card_id'), table_name='card_transactions')
    op.drop_table('card_transactions')
    op.drop_index(op.f('ix_card_limits_card_id'), table_name='card_limits')
    op.drop_table('card_limits')
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
