"""phase17_method_config

Revision ID: 9f704121249f
Revises: 9ee47bb79171
Create Date: 2026-06-21 18:04:46.107842
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '9f704121249f'
down_revision: Union[str, None] = '9ee47bb79171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_unique_constraint(None, 'admin_activity_logs', ['id'])
    op.create_unique_constraint(None, 'admin_permissions', ['id'])
    op.create_unique_constraint(None, 'admin_roles', ['id'])
    op.create_unique_constraint(None, 'admin_sessions', ['id'])
    op.create_unique_constraint(None, 'admins', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_constraint(None, 'admin_sessions', type_='unique')
    op.drop_constraint(None, 'admin_roles', type_='unique')
    op.drop_constraint(None, 'admin_permissions', type_='unique')
    op.drop_constraint(None, 'admin_activity_logs', type_='unique')
    op.drop_table('system_configs')
    # ### end Alembic commands ###
