"""phase4_deposits

Revision ID: e1fabe2a4ed7
Revises: 20a164cf82cd
Create Date: 2026-06-21 06:50:36.156053
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'e1fabe2a4ed7'
down_revision: Union[str, None] = '20a164cf82cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_networks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('network_type', sa.String(length=50), nullable=False),
    sa.Column('contract_address', sa.String(length=500), nullable=True),
    sa.Column('admin_wallet_address', sa.String(length=500), nullable=False),
    sa.Column('min_confirmations', sa.String(length=10), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('block_explorer_url', sa.String(length=500), nullable=True),
    sa.Column('deep_link_scheme', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('crypto_transactions',
    sa.Column('tx_hash', sa.String(length=500), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('from_address', sa.String(length=500), nullable=True),
    sa.Column('to_address', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('confirmations', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deposit_session_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_crypto_transactions_deposit_session_id'), 'crypto_transactions', ['deposit_session_id'], unique=False)
    op.create_index(op.f('ix_crypto_transactions_tx_hash'), 'crypto_transactions', ['tx_hash'], unique=True)
    op.create_table('crypto_wallets',
    sa.Column('network_id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_cold_storage', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_crypto_wallets_network_id'), 'crypto_wallets', ['network_id'], unique=False)
    op.create_table('deposit_methods',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('fee_amount', sa.Float(), nullable=False),
    sa.Column('processing_time', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('requires_admin_approval', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('deposits',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('method_data', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_deposits_reference'), 'deposits', ['reference'], unique=True)
    op.create_index(op.f('ix_deposits_user_id'), 'deposits', ['user_id'], unique=False)
    op.create_table('deposit_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('deposit_id', sa.String(length=36), nullable=True),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=True),
    sa.Column('admin_address', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('tx_hash', sa.String(length=500), nullable=True),
    sa.Column('confirmed_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_deposit_sessions_user_id'), 'deposit_sessions', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'account_balances', ['id'])
    op.create_unique_constraint(None, 'account_statements', ['id'])
    op.create_unique_constraint(None, 'accounts', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_constraint(None, 'account_statements', type_='unique')
    op.drop_constraint(None, 'account_balances', type_='unique')
    op.drop_index(op.f('ix_deposit_sessions_user_id'), table_name='deposit_sessions')
    op.drop_table('deposit_sessions')
    op.drop_index(op.f('ix_deposits_user_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_reference'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_table('deposit_methods')
    op.drop_index(op.f('ix_crypto_wallets_network_id'), table_name='crypto_wallets')
    op.drop_table('crypto_wallets')
    op.drop_index(op.f('ix_crypto_transactions_tx_hash'), table_name='crypto_transactions')
    op.drop_index(op.f('ix_crypto_transactions_deposit_session_id'), table_name='crypto_transactions')
    op.drop_table('crypto_transactions')
    op.drop_table('crypto_networks')
    # ### end Alembic commands ###
