ALL_PERMISSIONS = {
    "users.view": "View users list",
    "users.detail": "View user details",
    "users.edit": "Edit user profile",
    "users.suspend": "Suspend/Activate users",
    "users.delete": "Delete users",
    "users.kyc": "Manage KYC approvals",
    "users.limits": "Override user limits",
    "users.balance": "Adjust user balance",
    "users.accounts": "Manage user accounts",
    "users.cards": "Manage user cards",
    "users.security": "Reset passwords/2FA",
    "users.sessions": "Force logout users",
    "users.notes": "Add internal notes",
    "users.tags": "Manage user tags",
    "transactions.view": "View all transactions",
    "transactions.approve": "Approve deposits/withdrawals",
    "transactions.reject": "Reject deposits/withdrawals",
    "transactions.reverse": "Reverse transactions",
    "transactions.flag": "Flag/unflag transactions",
    "transactions.bulk": "Bulk operations",
    "transactions.export": "Export transactions",
    "methods.view": "View method configs",
    "methods.edit": "Edit method configs",
    "reports.view": "View reports",
    "reports.export": "Export reports",
    "admins.view": "View admin accounts",
    "admins.create": "Create admin accounts",
    "admins.edit": "Edit admin accounts",
    "admins.delete": "Delete admin accounts",
    "roles.view": "View roles",
    "roles.create": "Create roles",
    "roles.edit": "Edit roles",
    "roles.delete": "Delete roles",
    "permissions.assign": "Assign permissions",
    "audit.view": "View audit logs",
    "audit.export": "Export audit logs",
    "system.settings": "Manage system settings",
    "system.templates": "Manage email/SMS templates",
    "system.legal": "Manage legal documents",
    "notifications.send": "Send notifications",
}
